name: ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - 'release/*'
      - main

jobs:
  laravel-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: npm
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      - name: Install dependencies
        run: composer install -n --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Create database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Install more dependencies
        run: npm install
      - name: Build vite assets
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        run: npm run build
      - name: Run tests
        run: php artisan test
