name: composer audit

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: '8.4'

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          tools: composer
      - run: composer audit --locked --ignore-severity=low --ignore-severity=medium
